# Join and leave messages. Supports PlaceholderAPI and MiniMessage.
# Set a message to an empty string ("") to disable

join-message: "<gold>%player_name%<rainbow> joined the game!</rainbow>   <gray><hover:show_text:Click to DM %player_name%><click:suggest_command:/tell %player_name%>[DM]</click></hover>"
quit-message: "<gold>%player_name%</gold><red> left the game!"
