name: Update Dependency graph

on:
  push:
    branches: [ "main" ]

jobs:

  dependency-submission:

    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@ec92e829475ac0c2315ea8f9eced72db85bb337a # v3.0.0
