name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Clean
        run: ./gradlew clean

      - name: Run Tests
        run: ./gradlew test

      - name: KtLint
        run: ./gradlew ktlintCheck

      - name: Build
        run: ./gradlew build

      - name: Create Distribution ZIP
        run: ./gradlew zipDistribution

      - name: Generate Dependency Graph
        run: ./gradlew generateDependencyGraph

      - uses: actions/upload-artifact@v4
        with:
          #name: Basics-dist
          path: build/dist