on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
#      - name: Get short SHA
#        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
#      - name: Print short SHA
#        run: echo "The short SHA is $SHORT_SHA"
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a # v3.0.0
      - name: Build with Gradle Wrapper
        run: ./gradlew ktlintCheck test build zipDistribution
      - name: Create release
        uses: softprops/action-gh-release@v0.1.15
#        if: github.ref == 'refs/heads/main' # This condition makes the step run only for the main branch
        if: startsWith(github.ref, 'refs/tags/')
        with:
          #tag_name: ${{ env.SHORT_SHA }}
          files: |
            build/dist/basics-*.zip
          draft: false
          generate_release_notes: true
          append_body: false

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
      # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@ec92e829475ac0c2315ea8f9eced72db85bb337a # v3.0.0