name: Basics Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Release Basics
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          java-version: 17
          distribution: temurin
#          cache: 'gradle'

      - name: Get Tag name
        uses: olegtarasov/get-tag@v2.1.2
#        id: tagName

#      - name: Fetch all history for all tags and branches
#        run: git fetch --prune --unshallow

      - name: Update version in build.gradle.kts
        run: |
          GIT_REF=${{ steps.tagName.outputs.tag }} # not needed
          echo "Project version adjusted to $GIT_TAG_NAME"
          sed -i "s/version = \".*\"/version = \"$GIT_TAG_NAME\"/" build.gradle.kts

      - name: Build zip archive with Gradle Wrapper
        run: ./gradlew build zipDistribution --scan

#      - name: Run printVersion task and set env variable
#        run: |
#          VERSION=$(./gradlew printVersion --quiet)
#          echo "Project version is $VERSION"
#          echo "PROJECT_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Generate checksum
        run: |
          cd build/dist
          CHECKSUM=`sha256sum basics-$GIT_TAG_NAME.zip`
          cd ../..
          echo $CHECKSUM > checksum.txt
          echo -e "### SHA256 Checksum\n\`\`\`\n$CHECKSUM\n\`\`\`" > checksum_md.txt

      - name: Create release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            build/dist/basics-${{ env.GIT_TAG_NAME }}.zip
            checksum.txt
          draft: false
          generate_release_notes: true
          append_body: false
#          body_path: checksum_md.txt